export enum routes {
  DASHBOARD = '/dashboard',
  SECTIONS = '/home-sections',
  CAREERS = '/careers',
  STUDCORNER = '/stud-corner',
  ABOUTUS ='/aboutUs',
  PUBLIC_MEND ='/public-mend',
  C_ADMISSION ='/admission/create',
  CAT_ADMISSION ='/admission/category',
  MUL_ADMISSION ='/admission/multiple-import',
  STUDNT_LIST ='/student-details/student-list',
  STUDNT_DETAIL='/student-details',
  STUDNT_INFO='/student-details/student-info',
  EMP_LIST='/employee/list',
  EMP_DEPT='/employee/department',
  EMP_DES='/employee/designation',
  EMP_ADD='/employee/add',
  CERT_TEMP='/cert/template',
  CERT_STUD='/cert/student',
  CERT_EMP='/cert/employee',
  MARKS_ENTRY='/marks/entry',
  GRADE_RANGE='/marks/grade',
  WORK_LIST='/homework/list',
  WORK_NEW='/homework/list/add',
  EVAL_REPORT='/homework/report',
  BULK_SEND_SMS='/bulk/send-sms',
  BULK_SMS_REPORT='/bulk/sms-report',
  BULK_SMS_TEMP='/bulk/sms-temp',
  BULK_EMAIL_TEMP='/bulk/email-temp',
  BULK_STUD_BIRTH='/bulk/stud-birth',
  BULK_STAFF_BIRTH='/bulk/staff-birth',
  TRANS_ROUTE='/transport/route',
  TRANS_VEHICLE='/transport/vehicle',
  TRANS_STOP='/transport/stop',
  TRANS_ASSIGN='/transport/assign',
  TRANS_REPORT='/transport/report',
  RECEP_ENQUIRY='/reception/enquiry',
  RECEP_CALLLOG='/reception/calllog',
  RECEP_VISITORLOG='/reception/visitorlog',
  ACADE_CLASS='/academic/class',
  ACADE_ASSIGN='/academic/assign',
  ACADE_SUB='/academic/subject',
  ACADE_CLASS_ASSIGN='/academic/class-assign',
  ACADE_CLASS_SCH='/academic/class-schedule',
  ACADE_CLASS_SCH_ADD='/academic/class-schedule/add',
  ACADE_TEACHER_SCH='/academic/teacher-schedule',
  STUD_ACCOUNTING='/student-acconting/fees-type',
  STUD_FEES_GROUP='/student-acconting/fees-group',
  STUD_FINE_SETUP='/student-acconting/fine-setup',
  STUD_FESS_ALLOC='/student-acconting/fees-allocation',
  STUD_FESS_PAY_INVOI ="/student-acconting/fees-pay-invoice",
  INVOI ="/student-acconting/invoice/invoice-collect-paid",
  STUD_DUE_FEES_INVOI ="/student-acconting/due-fees-invoice",
  STUD_FEES_REMAINDER ="/student-acconting/fees-remainder",





  LOGIN = '/login'
}
