export enum routes {
  DASHBOARD = '/dashboard',
  SECTIONS = '/home-sections',
  CAREERS = '/careers',
  STUDCORNER = '/stud-corner',
  ABOUTUS ='/aboutUs',
  PUBLIC_MEND ='/public-mend',
  C_ADMISSION ='/admission/create',
  CAT_ADMISSION ='/admission/category',
  MUL_ADMISSION ='/admission/multiple-import',
  STUDNT_LIST ='/student-details/student-list',
  STUDNT_DETAIL='/student-details',
  STUDNT_INFO='/student-details/student-info',
  EMP_LIST='/employee/list',
  EMP_DEPT='/employee/department',
  EMP_DES='/employee/designation',
  EMP_ADD='/employee/add',
  CERT_TEMP='/cert/template',
  CERT_STUD='/cert/student',
  CERT_EMP='/cert/employee',
  MARKS_ENTRY='/marks/entry',
  GRADE_RANGE='/marks/grade',
  WORK_LIST='/homework/list',
  WORK_NEW='/homework/list/add',
  EVAL_REPORT='/homework/report',
  LOGIN = '/login'
}
